## Day 1 numpy--->(Numerical Python ❤😎😴)

In [1]:
import numpy as np

## Creating one dimensional array

In [2]:
my_list = [1,2,3,4,5]
my_list

[1, 2, 3, 4, 5]

In [3]:
np.array(my_list)

array([1, 2, 3, 4, 5])

## Creating two dimensional array

In [4]:
my_2darray = [[1,2,3],[4,5,6],[7,8,9]]
my_2darray

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
np.array(my_2darray)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Generate numbers in given range

In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,11,2) ##start,stop,stepsize

array([ 0,  2,  4,  6,  8, 10])

## used to create zero matrix

In [8]:
np.zeros(3) ##generates zeroes takes only one arg for shape

array([0., 0., 0.])

In [9]:
np.zeros((5,5)) ##desired dimensions using tuple

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## Used to create matrix with only value as 1

In [10]:
np.ones(3) ##generates ones takes one arg for shape

array([1., 1., 1.])

In [11]:
np.ones((3,3)) ##generates desired dimensions

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## linspace is used for evenly spaced numbers within the interval

In [12]:
np.linspace(0,10,3) #Return evenly spaced numbers over a specified interval.

array([ 0.,  5., 10.])

In [13]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## eye for identity matrix

In [14]:
np.eye(4) #generates identity matrix according to specified diensions

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## rand is used for uniform distribution between 0 and 1

In [15]:
np.random.rand(2) #uniform distribution between 0 and 1

array([0.86819453, 0.28033143])

In [16]:
np.random.rand(5,5) #uniform distribution between 0 and 1 with specific dimensions

array([[0.2635104 , 0.76393118, 0.18952179, 0.38334289, 0.00154722],
       [0.2755467 , 0.07369153, 0.24036738, 0.68690214, 0.3133243 ],
       [0.09256679, 0.28875498, 0.95769373, 0.78287179, 0.3093694 ],
       [0.99682129, 0.50834291, 0.60189564, 0.67946065, 0.19680504],
       [0.46092306, 0.97607999, 0.24115423, 0.76994238, 0.11168109]])

## randn is used for standard normal distribution

In [17]:
np.random.randn(2)

array([ 1.19616935, -0.7329041 ])

In [18]:
np.random.randn(5,5)

array([[ 1.99138812,  0.42003345,  0.53193732, -0.64093514, -0.26514243],
       [-2.31567256,  1.19500107, -0.37156075, -0.94040861,  1.03205484],
       [-0.32609288, -0.33113167, -0.06010839, -0.27508682,  0.94654753],
       [ 0.95177895,  1.02461881,  1.46413033, -0.33802876, -0.68911749],
       [-1.29289433, -2.39971332, -0.93666176, -0.8594106 , -0.49204484]])

In [19]:
np.random.randint(1,100)

79

In [20]:
np.random.randint(1,100,10) ##randomly generates integer values between low(included) and high(excluded) and the third arg is number of values

array([22,  1,  9, 92,  7, 33, 49, 34, 35, 47])

In [21]:
arr = np.arange(20)
ranarr = np.random.randint(0,80,10)

In [22]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [23]:
ranarr

array([41, 38, 21, 23, 76,  7, 75, 36, 44, 21])

In [24]:
arr.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [25]:
ranarr

array([41, 38, 21, 23, 76,  7, 75, 36, 44, 21])

In [26]:
ranarr.max() #returns maxval in array

76

In [27]:
ranarr.argmax() #returns index

4

In [28]:
ranarr.min() #returns min val in array

7

In [29]:
ranarr.argmin() #returns index of minval

5

In [30]:
arr.shape

(20,)

In [31]:
arr.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [32]:
arr.reshape(1,20).shape

(1, 20)

In [33]:
arr.reshape(20,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19]])

In [34]:
arr.reshape(20,1).shape

(20, 1)

In [35]:
arr.dtype

dtype('int32')

## working on indices of numpy

In [36]:
my_list2 = [1,2,3,4,5]
my_list2

[1, 2, 3, 4, 5]

In [37]:
arr2=np.array(my_list2)
arr2

array([1, 2, 3, 4, 5])

In [38]:
arr2[0:2]

array([1, 2])

In [39]:
arr3 = np.array([[1,2,3,4],[2,4,5,6],[3,5,6,7],[2,6,8,5]])
arr3

array([[1, 2, 3, 4],
       [2, 4, 5, 6],
       [3, 5, 6, 7],
       [2, 6, 8, 5]])

In [40]:
arr3[1]

array([2, 4, 5, 6])

In [41]:
arr3[0:2,1:3]

array([[2, 3],
       [4, 5]])

In [42]:
arr4 = np.arange(1,8)
arr4

array([1, 2, 3, 4, 5, 6, 7])

## Selection of comparison operators

In [43]:
arr_true_false = arr4 < 3
arr_true_false

array([ True,  True, False, False, False, False, False])

In [44]:
arr4[arr_true_false]

array([1, 2])

## Numpy Operations

In [45]:
arr_oper1 = np.random.randint(1,10,10)
arr_oper1

array([3, 5, 1, 6, 3, 5, 4, 9, 5, 7])

In [46]:
arr_oper2 = np.random.randint(0,8,10)
arr_oper2

array([0, 5, 2, 7, 6, 4, 3, 0, 1, 5])

In [47]:
arr_oper1 + arr_oper2

array([ 3, 10,  3, 13,  9,  9,  7,  9,  6, 12])

In [48]:
arr_oper1 - arr_oper2

array([ 3,  0, -1, -1, -3,  1,  1,  9,  4,  2])

In [49]:
arr_oper1 * arr_oper2

array([ 0, 25,  2, 42, 18, 20, 12,  0,  5, 35])

In [50]:
arr_oper1 ** arr_oper2

array([     1,   3125,      1, 279936,    729,    625,     64,      1,
            5,  16807], dtype=int32)

In [51]:
arr_oper1 / arr_oper2

C:\Users\SHARUK~1\AppData\Local\Temp/ipykernel_6196/2208851111.py:1: RuntimeWarning: divide by zero encountered in true_divide
  arr_oper1 / arr_oper2


array([       inf, 1.        , 0.5       , 0.85714286, 0.5       ,
       1.25      , 1.33333333,        inf, 5.        , 1.4       ])

In [52]:
np.sin(arr_oper2)

array([ 0.        , -0.95892427,  0.90929743,  0.6569866 , -0.2794155 ,
       -0.7568025 ,  0.14112001,  0.        ,  0.84147098, -0.95892427])

In [53]:
np.exp(arr_oper2)

array([1.00000000e+00, 1.48413159e+02, 7.38905610e+00, 1.09663316e+03,
       4.03428793e+02, 5.45981500e+01, 2.00855369e+01, 1.00000000e+00,
       2.71828183e+00, 1.48413159e+02])

In [54]:
np.log(arr_oper1)

array([1.09861229, 1.60943791, 0.        , 1.79175947, 1.09861229,
       1.60943791, 1.38629436, 2.19722458, 1.60943791, 1.94591015])